"""Pool de rankings globales EN — canal #11 Global Rankings (bar chart race).

Reusa el generador de `ranking` vía `RankingBranding(lang="en", ...)`. Contenido
NUEVO en inglés (NO traducción del pool ES): rankings globales evergreen con
fuente pública citable. Schema idéntico al de ranking ES para reusar el generador.
YMYL excluido (sin salud/medicina/política/cripto/inversión). Cooldown 90 días.
"""
from __future__ import annotations


TOPICS = [
    {"key": "gdp_countries", "audiencia": "general", "categoria": "economy",
     "titulo": "Top 10 countries by GDP · 2000-2026",
     "fuente": "World Bank / IMF",
     "dataset_hint": "Nominal GDP in USD trillion, G20 top 10, China rise vs USA",
     "cifra_ancla": "USD trillion"},
    {"key": "population_countries", "audiencia": "general", "categoria": "demographics",
     "titulo": "Top 10 most populous countries · 1950-2026",
     "fuente": "UN Population Division",
     "dataset_hint": "Population in millions, India overtook China in 2023",
     "cifra_ancla": "million people"},
    {"key": "brand_value", "audiencia": "general", "categoria": "business",
     "titulo": "Top 10 most valuable brands · 2000-2026",
     "fuente": "Interbrand / Kantar BrandZ",
     "dataset_hint": "Apple/Microsoft/Google/Amazon rise vs Coca-Cola/IBM in 2000",
     "cifra_ancla": "USD billion brand value"},
    {"key": "megacities_2050", "audiencia": "general", "categoria": "demographics",
     "titulo": "Top 15 megacities in the world · 2050 projection",
     "fuente": "UN World Urbanization Prospects",
     "dataset_hint": "Tokyo, Delhi, Shanghai, Dhaka, Lagos, Mumbai projections",
     "cifra_ancla": "million urban residents"},
    {"key": "richest_people", "audiencia": "general", "categoria": "economy",
     "titulo": "Top 10 richest people in the world · 2000-2026",
     "fuente": "Forbes billionaires list",
     "dataset_hint": "Gates 2000s then Bezos/Musk/Arnault 2020s, yearly net worth",
     "cifra_ancla": "USD billion net worth"},
    {"key": "youtube_subscribers", "audiencia": "general", "categoria": "internet",
     "titulo": "Top 10 YouTube channels by subscribers · 2010-2026",
     "fuente": "Social Blade historical",
     "dataset_hint": "T-Series, MrBeast, PewDiePie, Cocomelon, Kids Diana",
     "cifra_ancla": "million subscribers"},
    {"key": "champions_scorers", "audiencia": "sports", "categoria": "football",
     "titulo": "Top 20 UEFA Champions League scorers · all-time",
     "fuente": "UEFA official statistics",
     "dataset_hint": "Ronaldo ~140, Messi ~129, Lewandowski 100+",
     "cifra_ancla": "Champions League goals"},
    {"key": "box_office_actors", "audiencia": "general", "categoria": "film",
     "titulo": "Top 15 highest-grossing actors · 2000-2026",
     "fuente": "Box Office Mojo",
     "dataset_hint": "Downey Jr, Scarlett Johansson, Samuel L. Jackson, Zoe Saldana",
     "cifra_ancla": "USD billion box office"},
    {"key": "best_selling_cars", "audiencia": "general", "categoria": "consumer",
     "titulo": "Top 15 best-selling cars of all time",
     "fuente": "Manufacturer reports + JATO",
     "dataset_hint": "Toyota Corolla 50M+, Ford F-Series, VW Golf/Beetle",
     "cifra_ancla": "million units"},
    {"key": "highest_grossing_films", "audiencia": "general", "categoria": "film",
     "titulo": "Top 20 highest-grossing films · all-time",
     "fuente": "Box Office Mojo",
     "dataset_hint": "Avatar, Avengers Endgame, Titanic, Star Wars, worldwide gross",
     "cifra_ancla": "USD billion box office"},
    {"key": "best_selling_artists", "audiencia": "general", "categoria": "music",
     "titulo": "Top 15 best-selling music artists · 1950-2026",
     "fuente": "IFPI / RIAA certifications",
     "dataset_hint": "Beatles, Elvis, Michael Jackson, Madonna, Taylor Swift",
     "cifra_ancla": "million records certified"},
    {"key": "olympic_medals", "audiencia": "sports", "categoria": "sports",
     "titulo": "Top 10 countries by Olympic medals · 1896-2026",
     "fuente": "IOC official history",
     "dataset_hint": "USA leads, USSR/Russia, China rise post-2000, GB, Germany",
     "cifra_ancla": "total medals"},
    {"key": "military_spending", "audiencia": "general", "categoria": "economy",
     "titulo": "Top 10 countries by military spending · 2000-2026",
     "fuente": "SIPRI",
     "dataset_hint": "USA far ahead, China rise, Russia, India, Saudi Arabia",
     "cifra_ancla": "USD billion"},
    {"key": "most_visited_countries", "audiencia": "general", "categoria": "travel",
     "titulo": "Top 10 most visited countries · 2000-2026",
     "fuente": "UN Tourism (UNWTO)",
     "dataset_hint": "France, Spain, USA, China, Italy — international arrivals",
     "cifra_ancla": "million international arrivals"},
    {"key": "smartphone_brands", "audiencia": "general", "categoria": "tech",
     "titulo": "Top 10 smartphone brands by market share · 2010-2026",
     "fuente": "IDC / Counterpoint Research",
     "dataset_hint": "Nokia/BlackBerry fall, Apple/Samsung/Xiaomi rise",
     "cifra_ancla": "percent global market share"},
    {"key": "richest_football_clubs", "audiencia": "sports", "categoria": "football",
     "titulo": "Top 10 richest football clubs · 2010-2026",
     "fuente": "Deloitte Football Money League",
     "dataset_hint": "Real Madrid, Man City, Barcelona, Man United, Bayern revenue",
     "cifra_ancla": "EUR million revenue"},
    {"key": "most_spoken_languages", "audiencia": "general", "categoria": "society",
     "titulo": "Top 15 most spoken languages in the world",
     "fuente": "Ethnologue",
     "dataset_hint": "English, Mandarin, Hindi, Spanish — total speakers",
     "cifra_ancla": "million speakers"},
    {"key": "tallest_buildings", "audiencia": "general", "categoria": "engineering",
     "titulo": "Top 15 tallest buildings in the world · 2000-2026",
     "fuente": "CTBUH",
     "dataset_hint": "Burj Khalifa, Merdeka 118, Shanghai Tower — height in meters",
     "cifra_ancla": "meters tall"},
    {"key": "most_followed_instagram", "audiencia": "general", "categoria": "internet",
     "titulo": "Top 10 most-followed Instagram accounts · 2015-2026",
     "fuente": "Instagram / Social Blade",
     "dataset_hint": "Instagram, Ronaldo, Messi, Selena Gomez — followers",
     "cifra_ancla": "million followers"},
    {"key": "car_manufacturers_sales", "audiencia": "general", "categoria": "business",
     "titulo": "Top 10 car manufacturers by sales · 2000-2026",
     "fuente": "OICA",
     "dataset_hint": "Toyota, VW Group, Hyundai-Kia, GM, Ford — units sold",
     "cifra_ancla": "million vehicles per year"},
    {"key": "biggest_companies_revenue", "audiencia": "general", "categoria": "business",
     "titulo": "Top 10 companies by revenue · 2000-2026",
     "fuente": "Fortune Global 500",
     "dataset_hint": "Walmart, Amazon, State Grid, Saudi Aramco, Apple",
     "cifra_ancla": "USD billion revenue"},
    {"key": "most_downloaded_apps", "audiencia": "general", "categoria": "tech",
     "titulo": "Top 10 most downloaded apps · 2015-2026",
     "fuente": "data.ai / Sensor Tower",
     "dataset_hint": "TikTok, Instagram, WhatsApp, Facebook — yearly downloads",
     "cifra_ancla": "million downloads"},
    {"key": "nba_scorers", "audiencia": "sports", "categoria": "sports",
     "titulo": "Top 15 NBA all-time scorers",
     "fuente": "NBA official statistics",
     "dataset_hint": "LeBron James, Kareem, Karl Malone, Kobe — career points",
     "cifra_ancla": "career points"},
    {"key": "most_streamed_spotify", "audiencia": "general", "categoria": "music",
     "titulo": "Top 10 most-streamed artists on Spotify · 2018-2026",
     "fuente": "Spotify Charts",
     "dataset_hint": "Bad Bunny, Taylor Swift, Drake, The Weeknd — total streams",
     "cifra_ancla": "billion streams"},
    {"key": "world_cup_winners", "audiencia": "sports", "categoria": "football",
     "titulo": "Top 10 countries by FIFA World Cup titles",
     "fuente": "FIFA official",
     "dataset_hint": "Brazil 5, Germany/Italy 4, Argentina 3 — titles over time",
     "cifra_ancla": "World Cup titles"},
]


def all_topics() -> list[dict]:
    return list(TOPICS)


def by_key(key: str) -> dict | None:
    for t in TOPICS:
        if t["key"] == key:
            return t
    return None
